---
- name: Install python3 pip and other libs
  apt:
    pkg:
    - python3-pip 
    - libxcb-util-dev
    - build-essential
    state: present
  become: true

- name: Ensure boto and boto3 modules are installed
  pip:
    name: ['boto3', 'botocore']

- name: 'Create softlink to libxcb-util.so.0'
  file:
    src: /lib/x86_64-linux-gnu/libxcb-util.so.1
    dest: /lib/x86_64-linux-gnu/libxcb-util.so.0
    state: link
  become: true

- name: Install C64 assemblers
  apt:
    pkg:
    - acme
    state: present
  become: true

- name: Git clone cc65
  git:
    repo=https://github.com/cc65/cc65.git
    dest="{{ TOOLS_DIR }}/cc65"

- name: Build CC65
  command: 'make'
  args:
    chdir: "{{ TOOLS_DIR }}/cc65" 

- name: Add CC65 to PATH
  lineinfile:
    path: ~/shellenv.sh
    line: "export PATH=$PATH:$TOOLS_DIR/cc65/bin"
    state: present
    insertbefore: "# END ANSIBLE MANAGED BLOCK"

