---
- name: Install python3 pip and other libs
  apt:
    pkg:
    - python3-pip 
    - libxcb-util-dev
    state: present
  become: true

- name: Ensure boto and boto3 modules are installed
  pip:
    name: ['boto3', 'botocore']

- name: 'Create softlink to libxcb-util.so.0'
  file:
    src: /lib/x86_64-linux-gnu/libxcb-util.so.1
    dest: /lib/x86_64-linux-gnu/libxcb-util.so.0
    state: link
  become: true

- name: Install snap of VS Code
  snap:
    name: code
    classic: yes
  become: true

# - name: Install Visual Studio Code extension - TonyLandi.acmecrossassembler
#   command: '/snap/bin/code --install-extension TonyLandi.acmecrossassembler'

- name: Install Visual Studio Code extension - rosc.vs64
  command: '/snap/bin/code --install-extension rosc.vs64'

- name: Install Visual Studio Code extension - tlgkccampbell.code-ca65 
  command: '/snap/bin/code --install-extension tlgkccampbell.code-ca65'

